# Generated by Django 5.0.6 on 2026-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True),
        ),
    ]
