"""Initial migration

Revision ID: a645295d2e24
Revises: 
Create Date: 2026-09-22 21:48:56.052357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a645295d2e24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('current_role', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_key', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_session_key'), 'interview_sessions', ['session_key'], unique=True)
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('rewritten_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_table('interview_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('raw_report', sa.JSON(), nullable=True),
    sa.Column('pdf_file', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('interview_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcription_data', sa.JSON(), nullable=True),
    sa.Column('sentiment_data', sa.JSON(), nullable=True),
    sa.Column('emotion_data', sa.JSON(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_responses_id'), 'interview_responses', ['id'], unique=False)
    op.drop_index(op.f('coach_interviewquestion_session_id_5f737e9a'), table_name='coach_interviewquestion')
    op.drop_table('coach_interviewquestion')
    op.drop_table('coach_interviewreport')
    op.drop_index(op.f('coach_interviewsession_candidate_id_a35b2874'), table_name='coach_interviewsession')
    op.drop_index(op.f('coach_interviewsession_user_id_5d7fef4e'), table_name='coach_interviewsession')
    op.drop_table('coach_interviewsession')
    op.drop_table('auth_group')
    op.drop_table('django_q_schedule')
    op.drop_index(op.f('success_index'), table_name='django_q_task', sqlite_where=sa.text('"success"'))
    op.drop_table('django_q_task')
    op.drop_table('django_q_ormq')
    op.drop_index(op.f('coach_candidate_user_id_bfc9fca2'), table_name='coach_candidate')
    op.drop_table('coach_candidate')
    op.drop_table('auth_user')
    op.drop_index(op.f('coach_interviewresponse_session_id_2a4530ff'), table_name='coach_interviewresponse')
    op.drop_table('coach_interviewresponse')
    op.drop_index(op.f('django_session_expire_date_a5c62663'), table_name='django_session')
    op.drop_table('django_session')
    op.drop_index(op.f('auth_group_permissions_group_id_b120cbf9'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_permission_id_84c5c92e'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), table_name='django_content_type')
    op.drop_table('django_content_type')
    op.drop_index(op.f('auth_permission_content_type_id_2f476e4b'), table_name='auth_permission')
    op.drop_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('django_migrations')
    op.drop_index(op.f('auth_user_groups_group_id_97559544'), table_name='auth_user_groups')
    op.drop_index(op.f('auth_user_groups_user_id_6a12ed8b'), table_name='auth_user_groups')
    op.drop_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), 'auth_user_groups', ['user_id', 'group_id'], unique=1)
    op.create_index(op.f('auth_user_groups_user_id_6a12ed8b'), 'auth_user_groups', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_groups_group_id_97559544'), 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('applied', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), 'auth_permission', ['content_type_id', 'codename'], unique=1)
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), 'django_content_type', ['app_label', 'model'], unique=1)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), 'auth_group_permissions', ['group_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', sa.TEXT(), nullable=False),
    sa.Column('expire_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('coach_interviewresponse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_index', sa.INTEGER(), nullable=False),
    sa.Column('duration_seconds', sa.REAL(), nullable=False),
    sa.Column('transcript', sa.TEXT(), nullable=False),
    sa.Column('transcription_data', sa.TEXT(), nullable=False),
    sa.Column('sentiment_data', sa.TEXT(), nullable=False),
    sa.Column('emotion_data', sa.TEXT(), nullable=False),
    sa.Column('audio_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('video_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('session_id', sa.CHAR(length=32), nullable=False),
    sa.CheckConstraint('"question_index" >= 0'),
    sa.CheckConstraint('(JSON_VALID("emotion_data") OR "emotion_data" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("sentiment_data") OR "sentiment_data" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("transcription_data") OR "transcription_data" IS NULL)'),
    sa.ForeignKeyConstraint(['session_id'], ['coach_interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_index', name=op.f('unique_session_response_index'))
    )
    op.create_index(op.f('coach_interviewresponse_session_id_2a4530ff'), 'coach_interviewresponse', ['session_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_candidate',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('current_role', sa.VARCHAR(length=150), nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=150), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('coach_candidate_user_id_bfc9fca2'), 'coach_candidate', ['user_id'], unique=False)
    op.create_table('django_q_ormq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('lock', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_q_task',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('func', sa.VARCHAR(length=256), nullable=False),
    sa.Column('hook', sa.VARCHAR(length=256), nullable=True),
    sa.Column('args', sa.TEXT(), nullable=True),
    sa.Column('kwargs', sa.TEXT(), nullable=True),
    sa.Column('result', sa.TEXT(), nullable=True),
    sa.Column('started', sa.DATETIME(), nullable=False),
    sa.Column('stopped', sa.DATETIME(), nullable=False),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('group', sa.VARCHAR(length=100), nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), nullable=False),
    sa.Column('cluster', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('success_index'), 'django_q_task', ['group', 'name', 'func'], unique=False, sqlite_where=sa.text('"success"'))
    op.create_table('django_q_schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('func', sa.VARCHAR(length=256), nullable=False),
    sa.Column('hook', sa.VARCHAR(length=256), nullable=True),
    sa.Column('args', sa.TEXT(), nullable=True),
    sa.Column('kwargs', sa.TEXT(), nullable=True),
    sa.Column('repeats', sa.INTEGER(), nullable=False),
    sa.Column('next_run', sa.DATETIME(), nullable=True),
    sa.Column('task', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('minutes', sa.INTEGER(), nullable=True),
    sa.Column('cron', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cluster', sa.VARCHAR(length=100), nullable=True),
    sa.Column('schedule_type', sa.VARCHAR(length=2), nullable=False),
    sa.Column('intended_date_kwarg', sa.VARCHAR(length=100), nullable=True),
    sa.CheckConstraint('"minutes" >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_interviewsession',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=150), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ai_model', sa.VARCHAR(length=120), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=False),
    sa.Column('candidate_id', sa.CHAR(length=32), nullable=False),
    sa.Column('session_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['coach_candidate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('coach_interviewsession_user_id_5d7fef4e'), 'coach_interviewsession', ['user_id'], unique=False)
    op.create_index(op.f('coach_interviewsession_candidate_id_a35b2874'), 'coach_interviewsession', ['candidate_id'], unique=False)
    op.create_table('coach_interviewreport',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('overall_score', sa.REAL(), nullable=False),
    sa.Column('confidence_score', sa.REAL(), nullable=False),
    sa.Column('sentiment_score', sa.REAL(), nullable=False),
    sa.Column('stress_score', sa.REAL(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('suggestions', sa.TEXT(), nullable=False),
    sa.Column('raw_report', sa.TEXT(), nullable=False),
    sa.Column('pdf_file', sa.VARCHAR(length=100), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.Column('session_id', sa.CHAR(length=32), nullable=False),
    sa.CheckConstraint('(JSON_VALID("raw_report") OR "raw_report" IS NULL)'),
    sa.CheckConstraint('(JSON_VALID("suggestions") OR "suggestions" IS NULL)'),
    sa.ForeignKeyConstraint(['session_id'], ['coach_interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_interviewquestion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('index', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('rewritten_text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('session_id', sa.CHAR(length=32), nullable=False),
    sa.CheckConstraint('"index" >= 0'),
    sa.ForeignKeyConstraint(['session_id'], ['coach_interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'index', name=op.f('unique_session_question_index'))
    )
    op.create_index(op.f('coach_interviewquestion_session_id_5f737e9a'), 'coach_interviewquestion', ['session_id'], unique=False)
    op.drop_index(op.f('ix_interview_responses_id'), table_name='interview_responses')
    op.drop_table('interview_responses')
    op.drop_table('interview_reports')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_sessions_session_key'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
